# Generated by Django 4.0.3 on 2022-04-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_post_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='mypage/files/%Y/%m/%d/'),
        ),
    ]
