# Generated by Django 4.0.3 on 2022-04-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='apply',
            field=models.CharField(max_length=500),
        ),
    ]
