# Generated by Django 4.0.3 on 2022-04-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_act_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='poster_image',
            field=models.ImageField(blank=True, upload_to='activity/images/{self.title}'),
        ),
    ]
